= Introduction à la programmation fonctionnelle (avec Haskell)
:source-highlighter: pygments
:icons: font
:source-language: haskell

.idée
====
* la fonction est un mapping entre un ensemble de valeur
* currying
* la fonction est une valeur comme une autre
* dans `a -> b`, `a` peut être une fonction
* jeu pour déterminer ce que fait une fonction à partir de sa signature
* opposé pureté et effet (un programme pure ne fait que chauffer le processeur)
* functor et monade ?
====

Depuis quelques années maintenant la programmation fonctionnelle à le vent en poupe,
si comme moi vous êtes un javaiste vous avez vu l'arrivée des lambdas.
Mais la programmation fonctionnelle ne se résume pas à des lambdas (et Java reste fondamentalement un language orienté objet).
Donc partons à la découverte de la programmation fonctionnelle avec un language qui s'en revendique pleinement : https://www.haskell.org/[Haskell]

== A l'origine il y avait la fonction

Avant de commencer nos pérégrinations, il faut préciser ce qu'est une fonction.
Dans le contexte de la programmation fonctionnelle il s'agit d'une opération qui transforme une valeur en une autre et cela sans effet de bord.
Penchons-nous de plus prêt sur ces 2 concepts.

Prenons par exemple la fonction `length` qui retourne la taille d'une chaine de caractère:

[source]
----
Prelude> length "hello" -- <1>
5
----

<1> pas besoin de parenthèse pour appeler une fonction, on passe les arguments avec des espaces entre chaque.

On peut également voir cette fonction comme une `Map` ayant comme clé une chaine de caratère et comme valeur la taille de la chaine,
mais comme vous l'imaginez, écrire une fonction comme ceci prendrait un peu de temps donc on fait un calcul plutôt qu'un mapping.

Pour que ce concept de fonction comme un mapping de valeurs tienne il faut que la fonction soit *pure*.
Une fonction pure c'est une fonction:

* qui ne dépend pas d'un contexte externe (variable globale, élément aléatoire...).
* qui ne produit pas d'effet (logger, écrire dans un fichier...).
* qui ne s'appuie que sur les arguments qu'on lui passe pour produire un résultat.

Ainsi le résultat d'une fonction pure sera toujours le même pourvu qu'on lui donne les mêmes arguments.

pureté !== effet

[NOTE]
On reviendra plus tard sur les fonctions à plusieurs arguments.


=== Effet 
== Pureté 


== Composition
