sudo: required

services:
  - docker                  

before_install:            
  - mkdir -p output
  - docker pull asciidoctor/docker-asciidoctor

script:
  - docker run -v $TRAVIS_BUILD_DIR:/documents/ --name asciidoc-to-html asciidoctor/docker-asciidoctor asciidoctor -D /documents/output -o index.html article.adoc      

after_error: 
  - docker logs asciidoc-to-html

after_failure:
  - docker logs asciidoc-to-html

after_success:      
  - cd output 
  - git init
  - git config user.name "${GH_USER_NAME}"
  - git config user.email "{GH_USER_EMAIL}"
  - git add . ; git commit -m "Deploy ${TRAVIS_COMMIT_RANGE} to GitHub Pages"
  - git log --oneline
  - git push --force "https://${GH_TOKEN}@${GH_REF}" master:gh-pages
  