= C'est quoi le fonctionnel dans programmation fonctionnelle ?
:source-highlighter: pygments
:pygments-style: manni
:icons: font
:source-language: haskell
:samplesdir: ./samples

Depuis quelques années maintenant la programmation fonctionnelle à le vent en poupe,
si comme moi vous êtes un javaiste vous avez vu l'arrivée des lambdas.
Mais Java (entre autre) reste attaché au paradigme objet.
Donc partons à l'aventure au pays des fonctions et des lambdas.

== Dis papa c'est quoi une lambda ?

Une lambda c'est tout simplement une fonction anonyme, ça passera mieux avec un exemple:

[source,java]
----
include::{samplesdir}/Lambda.java[]
----

Ici on utilise l'API Stream de Java 8 pour doubler chaque nombre du `Stream`.
`map` applique successivement la lambda `x -> x * 2` à chaque élément du `Stream`.

Ce que nous apporte l'utilisation d'une lambda c'est la concision, la lecture du code nous informe tout de suite de ce que l'on veut faire : multiplier un nombre par 2.
Comment est appliqué la lambda dépendra de l'appelant (ici `map`).

=== Et les closures dans tout ça ?

Une closure ressemble à une lambda mais elle embarque en plus un *contexte*:

[source,java]
----
include::{samplesdir}/Closure.java[]
----

Avez vous devinez pourquoi `x -> x + i` est un closure ?
Elle n'a pas de nom comme une lambda mais d'où vient le `i` ?
De la méthode `add`, la variable `i` fait parti du contexte dont on parlait. 
Lorsque la fonction `x -> x + i` s'exécutera, le `i` viendra du contexte de la closure.

== les fonctions en Haskell

On va maintenant 

=== quelques éléments de grammaire Haskell (par exemple les signatures de type)

== correspondance entre fonction “normale” et “lambda”

== passage de fonction en arguments (ou dans des collections)

== curryfication et application partielle

== composition de fonction FTW 

== conclusion

On a vu que dans un langage fonctionnel, une fonction est une valeur comme une autre que l'on peut aisément manipuler. 
La programmation fonctionnelle propose un nouveau challenge car on change de paradigme, 
au délà d'apprendre une nouvelle syntaxe il faut réussir à penser en terme de fonction: quand les injecter, les enchainer...

Je vous encourage vivement à apprendre la programmation fonctionnelle (avec Haskell en particulier, car vous serez contraint d'utiliser ce paradigme),
pour vous améliorez en tant que développeur.
Même si je continues à coder en Java au jour le jour, j'essaye de rendre mes fonctions le plus pure possible pour séparer aisément les calculs des effets.
