== Jouons avec les `List`

On va parler de la collection préférée des développeurs, les `List`.
Comme vu précédement, avec Haskell une liste se créée avec le constructeur `[]`, comme ceci `[1,2,3]` qui nous donne une magnifique liste d'entier.
Mais une liste peut contenir n'importe quel type, on dit qu'elle est polymorphique (pour un javaiste on parle de générique).
Donc on peut faire également ceci : `["foo", "bar", "baz"]` pour obtenir une liste de `String`.

NOTE: le type `String` est lui même une liste de `Char`, donc toutes les opérations concernant des listes peuvent lui être appliqué.

Commençons par concaténer notre liste, on utilise pour cela la fonction `++`:

[source, haskell,linenums]
----
*Main> [1,2] ++ [3,4]
[1,2,3,4]
----

Poursuivons avec la fonction `filter`, tout d'abord regardons son type

[source, haskell,linenums]
----
*Main> :t filter
filter :: (a -> Bool) -> [a] -> [a]
----

`filter` est une fonction prenant 2 paramètres :

* une fonction `a -> Bool` soit un prédicat que l'on appliquera.
* une liste de `a`, celle que l'on veut filtrer.

et retourne une nouvelle liste de `a`.
Donc `filter` va appliquer le *prédicat* à chacun des éléments de la liste,
si le *prédicat* est validé alors la valeur se retrouvera dans la liste retourné

[source, haskell,linenums]
----
*Main> filter (\x -> x > 3) [1,2,3,4,5]
[4,5]
----

TIP: `\x -> x > 3` est une *lambda*.

Vous remarquerez que la liste originale n'est pas modifiée ni perdue,
une nouvelle liste est retournée par `filter`, vous feriez mieux de vous y habituez vous ne trouverez que ça en Haskell.

On va transformer notre liste, je vous présente `map`:

[source, haskell,linenums]
----
*Main> :t map
map :: (a -> b) -> [a] -> [b]
----

Ah! un peu de nouveauté, un deuxième type paramétré `b`,
`map` applique la fonction `a -> b` à tous les éléments de `[a]` pour obtenir une liste de `[b]`.

Regardons le à l'oeuvre:

[source, haskell,linenums]
----
*Main> map length ["hello", "Haskell", "you're", "awesome"]
[5,7,6,7]
----

Comme vous pouvez le voir, on a transformé une `[String]` en `[Int]` en comptant le nombre de caractère de chaque mot de la liste.

[NOTE]
.Higher order function
====
On dit d'une fonction prenant (ou retournant) une autre fonction qu'elle est de haut niveau.
====